server:
  port: 8000

spring:
  application:
    name: %artifactId%
  profiles:
    active: ${run.spring.profile:%mvn.spring.profile%}
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  web:
    resources:
      static-locations: classpath:/static/
  mail:
    host: sg-smtp.qcloudmail.com
    port: 465
    username: official@coinhoho.com
    password: OfficialCoinhoho123

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

logging:
  level:
    root: error

xxl:
  job:
    accessToken:
    ### can choose "zh_CN", "zh_TC" and "en")
    i18n: zh_CN
    triggerpool:
      fast:
        ## xxl-job, triggerpool max size
        max: 200
      slow:
        max: 100
    ### xxl-job, log retention days
    logretentiondays: 30

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://127.0.0.1:5432/grab?schema=public
    username: postgres
    password: 123456

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://127.0.0.1:5432/monitoring_contract?schema=public
    username: monitoring_admin
    password: 123456

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://127.0.0.1:5432/monitoring_contract?schema=public
    username: monitoring_admin
    password: 123456